services:
  # --- База данных ---
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: my-app-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-web-platform}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # МАГИЯ ТУТ: кладем скрипт инициализации в спец. папку Postgres
      - ./database/design.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # --- Бэкенд ---
  backend:
    build: ./backend
    container_name: my-app-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=db # Обязательно 'db', так как это имя сервиса выше
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - DB_NAME=${DB_NAME:-web-platform}
    depends_on:
      - db

  # --- Фронтенд ---
  frontend:
    build: ./frontend
    container_name: my-app-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    stdin_open: true
    tty: true

  mailpit:
    image: axllent/mailpit
    container_name: logix-mailpit
    ports:
      - "8025:8025" # Веб-интерфейс (откроешь в браузере)
      - "1025:1025" # SMTP сервер (сюда бэк будет слать почту)
    restart: unless-stopped

volumes:
  postgres_data:
